fix: adjust requestGetRaw() to retry on requests_cache error
Some requests cause requests_cache to traceback with "AttibuteError:
'dict' object has no attribute 'raw'". Try to work around this by
retrying the failed request without the cache.