fix: require requests 2.28.2 and requests_cache 1.0.1
requests_cache 1.0.1 when used with requests 2.29.0 raises the following
exception when calling requests.get(..., allow_redirects=True) (the
default) when receiving a 301 from GitHub (eg, with issues):

  AttributeError: 'dict' object has no attribute 'raw'

The latest requests_cache version (1.0.1) specifies requests 2.28.2 in
its poetry.lock file and this version avoids this problem. As such, pin
both versions.